pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                script {
                    echo "Cleaning up workspace..."
                    sh 'rm -rf *'

                    echo "Cloning repository..."
                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: '*/main']],
                        userRemoteConfigs: [[
                            url: 'git@github.com:satishgonella2024/Jenkins-docker-rbac.git',
                            credentialsId: ''  // Leave blank for SSH-based authentication
                        ]]
                    ])
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t myusername/jenkins-docker-sample:latest .'
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline succeeded!"
        }
        failure {
            echo "Pipeline failed. Check logs for errors."
        }
    }
}
