pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                script {
                    echo "Cleaning workspace..."
                    sh 'rm -rf *'

                    echo "Fetching code..."
                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: 'refs/heads/main']],
                        userRemoteConfigs: [[
                            url: 'git@github.com:satishgonella2024/Jenkins-docker-rbac.git',
                            credentialsId: ''  // Leave blank for SSH-based auth
                        ]]
                    ])
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Build placeholder"
            }
        }
    }

    post {
        success {
            echo "Pipeline succeeded!"
        }
    }
}
