pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS = credentials('docker-hub-creds')  // Jenkins credentials ID
        DOCKER_IMAGE = 'myusername/jenkins-docker-sample:latest' // Update with your Docker Hub username
    }

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/satishgonella2024/Jenkins-docker-rbac.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh '''
                echo $DOCKER_CREDENTIALS_PSW | docker login -u $DOCKER_CREDENTIALS_USR --password-stdin
                docker push $DOCKER_IMAGE
                '''
            }
        }
    }

    post {
        success {
            echo "Pipeline succeeded! Docker image pushed to Docker Hub: $DOCKER_IMAGE"
        }
        failure {
            echo "Pipeline failed. Check logs for details."
        }
    }
}

