version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"        # Jenkins UI
      - "50000:50000"      # Agent communication
    volumes:
      - jenkins_home:/var/jenkins_home  # Persistent storage
    networks:
      - cicd
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:  # Persistent Jenkins data

networks:
  cicd:

